name: routeflow_logistics

profile: routeflow_logistics

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"


models:
  routeflow_logistics:
    gold_layer:
      +materialized: table


    