sources:
  - name: routeflow_logistics
    database: ROUTEFLOW_DB
    schema: ROUTEFLOW_SCHEMA

    tables:
      - name: silver_routeflow

        columns:
          - name: shipment_id
            data_tests:
              - not_null:
                  config:
                    severity: error

              - unique:           
                  config:
                    severity: error

          - name: shipment_date
            data_tests:
              - not_null:
                  config:
                    severity: error

          - name: delivery_date

          - name: status
            data_tests:
              - not_null:
                  config:
                    severity: warn

              - accepted_values:
                  arguments:
                    values: ['Delivered', 'In Transit', 'Pending', 'Failed', 'Cancelled', 'Returned']
                  config:
                    severity: error

          - name: status_reason
            data_tests:
              - not_null:
                  config:
                    severity: warn

          - name: origin
            data_tests:
              - not_null:
                  config:
                    severity: error

          - name: destination
            data_tests:
              - not_null:
                  config:
                    severity: error

          - name: carrier
            data_tests:
              - not_null:
                  config:
                    severity: error

          - name: shipping_cost
            data_tests:
              - not_null:
                  config:
                    severity: error

          - name: created_at
            data_tests:
              - not_null:
                  config:
                    severity: warn

          - name: updated_at
            
